### ISSUE TITLE
scoop-search doesn't work and returns instantly

### ISSUE THREAD

**Issue by trallnag** [shilangyu/scoop-search#18]
```
scoop-search 1.1.0
```

It just does not work. Any idea how I could get more information out of it? `scoop-search.exe` seems to almost instantly exit.

```
PS C:\Users\GHXCA> scoop search notepad
'extras' bucket:
    notepad2-mod (4.2.25.998)
    notepad2 (4.2.25)
    notepad3 (5.20.722.1)
    notepadplusplus (8.1.9.3)

PS C:\Users\GHXCA> scoop-search.exe notepad
PS C:\Users\GHXCA>
```

The shim exists.

```
PS C:\Users\GHXCA> gcm scoop-search.exe

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     scoop-search.exe                                   0.0.0.0    C:\Users\GHXCA\scoop\shims\scoop-search.exe
```

**Comment by shilangyu** [comment]
Hey, sorry for this extremely late response. What is the exit status? Perhaps some problems with antivirus. No path in scoop-search leads to no output.

**Comment by xianzheTM** [comment]
I have the same problem.Because vrcruntime140.dll was missing. I installed this and solved it. https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by shilangyu** [comment]
Closing due to lack of response. Like I said, calling `scoop-search.exe` should **always** end with some output, even when no matches are found. 

What @xianzheTM said sounds plausible. Windows does not seem to feedback users on missing DLLs when calling a program from powershell (it might be in the exit code, hence why I asked about it), programs just get killed with no feedback. Calling an `exe` from `explorer.exe` GUI does trigger a missing DLL dialog.
