### ISSUE TITLE
Is it possible to use this with cmd.exe?

### ISSUE THREAD

**Issue by eggbean** [shilangyu/scoop-search#41]
I prefer to use cmd.exe interactively (I still use PowerShell for scripts), as I just find it's very nice with [clink](https://github.com/chrisant996/clink).

Is there any way I can use scoop-search with cmd?

**Comment by shilangyu** [comment]
Have you tried using it as is? I don't think scoop-search makes any assumptions about the underlying shell, its just a native binary.

Unless you are referring to the hook, which replaces `scoop search` (rather than using it with `scoop-search`). I have zero experience with cmd, so if you'd know how to hack such a hook together then I would be happy to include it. Here is how it is done for powershell (its just an ugly hack): https://github.com/shilangyu/scoop-search/blob/55a7861c4fef502daf5a0b2857872aa215cb8cc3/args.go#L25
