### ISSUE TITLE
scoop-search.exe v1.3.3 flagged as malicious by multiple security vendors

### ISSUE THREAD

**Issue by cw433** [shilangyu/scoop-search#44]
Please see Virustotal:
https://www.virustotal.com/gui/file/d5ab7d9d164571b21c38b137e47604b8f9785758ec6ae1b99b014bef8acca4b9/detection

**Comment by Lockszmith-GH** [comment]
Came here to report that Windows Defender marks it as malicious.

**Comment by eggbean** [comment]
I haven't noticed as I exclude the scoop directory from Windows Defender scanning. Obviously there is some risk to this, but I just have to trust the scoop package maintainers. I did this previously there had been a couple of packages with false positives due to the compression used on the binaries.

You can exclude the scoop directory in an elevated PowerShell prompt:

    Add-MpPreference -ExclusionPath "$($env:programdata)\scoop", "$($env:scoop)"

Or `where scoop-search.exe` and add that directory, which for me would be:

    Add-MpPreference -ExclusionPath "C:\ProgramData\scoop\shims"

**Comment by Lockszmith-GH** [comment]
Thanks @eggbean, while this might be ok for some, I'm sure the maintainer does not want their application flagged as malware.
+ with 29 vendors marking the latest scoop-search.exe as a Trojan, maintainer should check their build environment for risks on their end.

**Comment by redactedscribe** [comment]
My Malwarebytes also flagged this. `scoop-search` is automatically installed by WingetUI.

**Comment by shilangyu** [comment]
Dear all. Last 4 issues have been about exactly this, and I have closed all of them as a wontfix simply because there is nothing I can possibly do. But let me take a different approach:

I have zero experience with antimalware software so I urge you for help with this matter to get to the bottom of this. On my side: every dependency is up to date, which is actually only github.com/valyala/fastjson which does not have any dependencies of its own. Last commit was over a year ago and a quick glance over the repository does not reveal any issues. Furthermore, the dependencies of the CI runner (github actions) are also up to date and standard tools used by the community. The binary that is released on github is that one which is built by the CI. This is fully automatic. The Golang version used to build is also the most recent version.

If someone has experience in this area I would gladly accept help to understand where the problem lies. For instance, could anyone that has Golang installed try to build the project and see if the built binary is also flagged as malware?

After some digging I have found that windows antivirus software seems to just [not like Golang binaries](https://go.dev/doc/faq#virus). A few reports have said that signing the binaries has helped. This is totally unnecessary but if I have to do that then I will.

**Comment by mattcargile** [comment]
Sentinel One MDR flags this. I just use `sfsu search` now.

**Comment by shilangyu** [comment]
Taking look at sfsu inspired me to rewrite scoop-search to be faster and without a runtime to hopefully not be flaged by anti viruses. Hopefully will have results by the end of the weekend.

**Comment by shilangyu** [comment]
Initial results are encouraging, rewrote scoop-search in Zig https://github.com/shilangyu/scoop-search/pull/45. The implementation is naive, will resume work on it tomorrow. Once I am done scoop-search should be faster, smaller, and free of any runtime.

**Comment by redactedscribe** [comment]
Nice to see Zig in use. Hope the rewrite resolves this issue.

**Comment by shilangyu** [comment]
I finished the rewrite. In my tests it is currently about 1.3x faster than sfsu and VirusTotal seems to complain much less about the binary.

Before I do a proper release (I am afraid that if I do a github pre-release scoop will pick it up as an update) I would appreciate if you could give it a whirl and see if it works fine for you. I have pushed a temporary branch with the committed exe: https://github.com/shilangyu/scoop-search/blob/temp/zig-build/zig-out/bin/scoop-search.exe. Of course I encourage you to build the binary from source if you (understandably) do not want to download an untrusted binary from the internet, using `zig build -Doptimize=ReleaseFast`.

If I get a few confirmations that it is working fine, I will do a proper release so scoop can pick it up.

**Comment by MANICX100** [comment]
Can confirm working for me <3

Only 1 detection on virustotal (CyNet)

[https://www.virustotal.com/gui/file/bf276a7788271c9a80bcaae909e24957ce677d17af31b227ceef81808d89bf9a](https://www.virustotal.com/gui/file/bf276a7788271c9a80bcaae909e24957ce677d17af31b227ceef81808d89bf9a)

**Comment by Fubuchi** [comment]
Got unsupported 16bit application error on win 11
![image](https://github.com/shilangyu/scoop-search/assets/42483897/39de477b-4da2-4cef-80f9-5196024a785a)

**Comment by marticliment** [comment]
It appears to work for me too

**Comment by shilangyu** [comment]
Thank you everyone for help, I have release [v1.4.0](https://github.com/shilangyu/scoop-search/releases/tag/v1.4.0). Closing this for now, feel free to comment if new issues arise!

**Comment by kazum1kun** [comment]
The issue is indeed fixed on 1.4.0. No more positives from [Virustotal ](https://www.virustotal.com/gui/file/767e990ff0cecb9ddd5e7083984e44b04992ee3d96ea13e4f94d0e5058cda473) and the Windows Security
